version: '3'
services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - .env

  auth:
    build:
      context: ./auth
      dockerfile: ./apps/auth/Dockerfile
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - postgres
    volumes:
      - .:/usr/src/app #any changes in the root folder will be reflected in the container
      - /usr/src/app/node_modules #prevents the node_modules from being deleted when the container is rebuilt
    command: npm run start:dev auth

  api:
    build:
      context: ./api
      dockerfile: ./apps/api/Dockerfile
    ports:
      - 4000:5000
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - auth
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev api

  postgres:
    image: postgres:17
    env_file:
      - .env
    ports:
      - 5432:5432

  postgres_admin:
    image: dpage/pgadmin4
    depends_on:
      - postgres  
    ports:
      - 15432:80
    env_file:
      - .env
